### ISSUE TITLE
Bug when `ralio open TAXXXX`

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#16]
⚡ ralio open TA17979

/Users/igorescobar/Projects/ralio/lib/ralio.js:182
        story.Tasks = self.orderTasks(story.Tasks);
                                           ^
TypeError: Cannot read property 'Tasks' of undefined
    at Ralio.story (/Users/igorescobar/Projects/ralio/lib/ralio.js:182:44)
    at Request.Ralio.request [as _callback](/Users/igorescobar/Projects/ralio/lib/ralio.js:65:7)
    at Request.init.self.callback (/Users/igorescobar/Projects/ralio/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/Users/igorescobar/Projects/ralio/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/Users/igorescobar/Projects/ralio/node_modules/request/main.js:517:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)

**Comment by igorescobar** [comment]
Fixed in v0.2.0
