### ISSUE TITLE
ralio sprint throwing error

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#2]
Hi man!
Nice work with your client!

I'm experiencing this problems after execute the following: ralio sprint

/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:177
    fields.push(story.Blocked ? state.red : state.green);
                                                 ^
TypeError: Cannot read property 'green' of undefined
    at CLI.printStoryLine (/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:177:50)
    at CLI.sprint (/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:49:14)
    at Array.forEach (native)
    at CLI.sprint (/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:47:13)
    at Ralio.sprint (/usr/local/share/npm/lib/node_modules/ralio/lib/ralio.js:143:9)
    at Request.Ralio.bulk [as _callback](/usr/local/share/npm/lib/node_modules/ralio/lib/ralio.js:54:7)
    at Request.init.self.callback (/usr/local/share/npm/lib/node_modules/ralio/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/usr/local/share/npm/lib/node_modules/ralio/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:96:17)

**Comment by igorescobar** [comment]
Issue solved with pull request #3
