### ISSUE TITLE
Error when ~/.raliorc doesn't exist

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#6]
This is the stacktrace error when I try to execute a instruction to rally without the ~/.raliorc

fs.js:338
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/igorescobar/.raliorc'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.readFileSync (fs.js:182:15)
    at CLI.configure (/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:16:31)
    at new CLI (/usr/local/share/npm/lib/node_modules/ralio/lib/cli.js:10:8)
    at Command.<anonymous> (/usr/local/share/npm/lib/node_modules/ralio/bin/ralio:27:30)
    at Command.action (/usr/local/share/npm/lib/node_modules/ralio/node_modules/commander/lib/commander.js:234:8)
    at Command.EventEmitter.emit (events.js:126:20)
    at Command.parseArgs (/usr/local/share/npm/lib/node_modules/ralio/node_modules/commander/lib/commander.js:406:12)
    at Command.parse (/usr/local/share/npm/lib/node_modules/ralio/node_modules/commander/lib/commander.js:356:15)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/ralio/bin/ralio:69:9)

**Comment by igorescobar** [comment]
- already fixed wait for my pull request ;)

**Comment by igorescobar** [comment]
Pull request #8 fix this issue :)
